### PR TITLE
feat: Code completion/navigation for //SOURCES

### PR DESCRIPTION
**Pull request by linux-china**
Implement feature for #38   @maxandersen

### CODE REVIEW

**Comment by maxandersen** [comment]
Looks good but I suggest You add some tests to the existing tests for content assist.

**Review by maxandersen — APPROVED** [review]
i would have added some more complex nested completion tests but whats there is a start :)

**Comment by maxandersen** [comment]
@linux-china do you want to merge it ? otherwise i'll  do it today/tomorrow

**Comment by linux-china** [comment]
yes, you can merge and release it.

**Pull request merged**
