### PR TITLE
feat: Java version sync retry in case it fails for first

### PR DESCRIPTION
**Pull request by nandorholozsnyak**
- Renaming "jbang" dependency collector to "${module.name}-jbang"
- Introducing JBangJdkService.kt
- Notifying user about Java version change

Related to #44 and #45

### CODE REVIEW

**Comment by nandorholozsnyak** [comment]
@linux-china can you check it if it is valuable or not? Thanks.

**Comment by nandorholozsnyak** [comment]
Build is failing with these two problems:
```
Plugin dev.jbang.intellij.JBangPlugin:0.17.0 against IC-213.7172.12: 2 compatibility problems. 15 usages of experimental API
Compatibility problems (2):
    #Package 'com.intellij.buildsystem' is not found
        Package 'com.intellij.buildsystem' is not found along with its 3 classes.
        Probably the package 'com.intellij.buildsystem' belongs to a library or dependency that is not resolved by the checker.
        It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to **NoSuchClassError**.
        The following classes of 'com.intellij.buildsystem' are not resolved:
          Class com.intellij.buildsystem.model.unified.UnifiedDependency is referenced in
            dev.jbang.idea.externalsystem.JBangDependencyModifier.addDependency(Module module, UnifiedDependency descriptor) : void
            dev.jbang.idea.externalsystem.JBangDependencyModifier.removeDependency(Module module, UnifiedDependency descriptor) : void
            dev.jbang.idea.externalsystem.JBangDependencyModifier.updateDependency(Module module, UnifiedDependency oldDescriptor, UnifiedDependency newDescriptor) : void
          Class com.intellij.buildsystem.model.unified.UnifiedDependencyRepository is referenced in
            dev.jbang.idea.externalsystem.JBangDependencyModifier.addRepository(Module module, UnifiedDependencyRepository repository) : void
            dev.jbang.idea.externalsystem.JBangDependencyModifier.deleteRepository(Module module, UnifiedDependencyRepository repository) : void
          Class com.intellij.buildsystem.model.DeclaredDependency is referenced in
            dev.jbang.idea.externalsystem.JBangDependencyModifier.declaredDependencies(Module module) : List

    #Access to unresolved class com.intellij.externalSystem.ExternalDependencyModificator
        Class dev.jbang.idea.externalsystem.JBangDependencyModifier references an unresolved class com.intellij.externalSystem.ExternalDependencyModificator. This can lead to **NoSuchClassError** exception at runtime.


Plugin dev.jbang.intellij.JBangPlugin:0.17.0 against IC-221.4994.44: 2 compatibility problems. 1 usage of deprecated API. 15 usages of experimental API
Compatibility problems (2):
    #Package 'com.intellij.buildsystem' is not found
        Package 'com.intellij.buildsystem' is not found along with its 3 classes.
        Probably the package 'com.intellij.buildsystem' belongs to a library or dependency that is not resolved by the checker.
        It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to **NoSuchClassError**.
        The following classes of 'com.intellij.buildsystem' are not resolved:
          Class com.intellij.buildsystem.model.unified.UnifiedDependency is referenced in
            dev.jbang.idea.externalsystem.JBangDependencyModifier.addDependency(Module module, UnifiedDependency descriptor) : void
            dev.jbang.idea.externalsystem.JBangDependencyModifier.removeDependency(Module module, UnifiedDependency descriptor) : void
            dev.jbang.idea.externalsystem.JBangDependencyModifier.updateDependency(Module module, UnifiedDependency oldDescriptor, UnifiedDependency newDescriptor) : void
          Class com.intellij.buildsystem.model.unified.UnifiedDependencyRepository is referenced in
            dev.jbang.idea.externalsystem.JBangDependencyModifier.addRepository(Module module, UnifiedDependencyRepository repository) : void
            dev.jbang.idea.externalsystem.JBangDependencyModifier.deleteRepository(Module module, UnifiedDependencyRepository repository) : void
          Class com.intellij.buildsystem.model.DeclaredDependency is referenced in
            dev.jbang.idea.externalsystem.JBangDependencyModifier.declaredDependencies(Module module) : List

    #Access to unresolved class com.intellij.externalSystem.ExternalDependencyModificator
        Class dev.jbang.idea.externalsystem.JBangDependencyModifier references an unresolved class com.intellij.externalSystem.ExternalDependencyModificator. This can lead to **NoSuchClassError** exception at runtime.

```

@linux-china any good idea to resolve them? I do not think I have modified these things.

**Comment by linux-china** [comment]
No worry, and I will take a look today.

**Comment by nandorholozsnyak** [comment]
Thanks

**Comment by linux-china** [comment]
@nandorholozsnyak  plugin verify fixed, and you can take look at my reviews.  I will merge tomorrow and release new version.

**Comment by nandorholozsnyak** [comment]
> @nandorholozsnyak plugin verify fixed, and you can take look at my reviews. I will merge tomorrow and release new version.

Cool nice, I see no comments or anythings, is the code in good state? Would you like me to change something?

**Pull request merged**
